sld:
  length: 2
  mode: mixed     # digits | alpha | mixed

tld:
  length: 2       # only use TLDs with length <= this value (2 or 3)

tlds:
  # ccTLDs - Country Code Top-Level Domain / Freely registrable
  - ac
  - ag
  - ai
  - am
  - as
  - at
  - bz
  - cc
  - ch
  - cl
  - cm
  - cn
  - co
  - cx
  - de
  - dj
  - dm
  - fm
  - gg
  - gl
  - gs
  - gy
  - hk
  - hn
  - ht
  - id
  - im
  - in
  - io
  - is
  - it
  - je
  - jp
  - ke
  - ki
  - kr
  - kz
  - la
  - lc
  - li
  - lt
  - lv
  - ly
  - ma
  - mc
  - md
  - me
  - mg
  - mk
  - ml
  - mn
  - mo
  - mp
  - ms
  - mu
  - mx
  - nc
  - nl
  - no
  - nu
  - nz
  - pe
  - ph
  - pk
  - pl
  - pm
  - pr
  - pw
  - qa
  - re
  - ro
  - rs
  - ru
  - rw
  - sb
  - sc
  - se
  - sg
  - sh
  - si
  - sk
  - sl
  - sm
  - sn
  - so
  - sr
  - st
  - sx
  - tc
  - tf
  - tg
  - tj
  - tk
  - tl
  - tm
  - tn
  - to
  - tt
  - tv
  - tw
  - tz
  - ua
  - ug
  - uk
  - us
  - uy
  - uz
  - vc
  - ve
  - vg
  - vi
  - vn
  - vu
  - wf
  - ws
  - yt
  - za
  # gTLDs - Generic Top-Level Domain / Open to public
  - app
  - art
  - bar
  - bet
  - bid
  - bio
  - biz
  - bot
  - cam
  - car
  - ceo
  - com
  - dad
  - day
  - dev
  - dog
  - eat
  - eco
  - fan
  - fit
  - fly
  - foo
  - fox
  - fun
  - fyi
  - gay
  - gle
  - got
  - hot
  - how
  - ice
  - icu
  - inc
  - ing
  - ink
  - kim
  - lat
  - law
  - llc
  - lol
  - ltd
  - map
  - mba
  - med
  - men
  - moe
  - mom
  - mov
  - net
  - new
  - now
  - nyc
  - one
  - ooo
  - org
  - ovh
  - pay
  - pet
  - phd
  - pin
  - pro
  - pub
  - red
  - ren
  - rio
  - rip
  - run
  - sex
  - ski
  - sky
  - soy
  - spa
  - srl
  - tab
  - tax
  - tel
  - top
  - uno
  - vet
  - vin
  - vip
  - wed
  - win
  - wow
  - wtf
  - xin
  - xxx
  - xyz
  - you
  - zip

scanner:
  dnsConcurrency: 50
  rdapConcurrency: 20
  whoisDelay: 2000
  whoisRetries: 3
